# What is Plotly?

Plotly is a modern Python visualization library used for creating interactive and dynamic visualizations.

Unlike Matplotlib and Seaborn, Plotly graphs are:
- Interactive
- Zoomable
- Hover-enabled
- Presentation-friendly
- Web-compatible

This makes Plotly highly useful in real-world dashboards, business analytics, and data storytelling.

### Why Do We Use Plotly ?

### Interactivity
Plotly allows users to:
- Hover over data points
- Zoom into specific regions
- Toggle graph elements
- Explore data visually

### Better for Presentations & Dashboards
Plotly visualizations are widely used in:
- Business dashboards
- Data reports
- Web applications
- Analytical presentations

### Real-World Relevance
In industry, Plotly is commonly used alongside tools like Dash and Streamlit to build interactive data apps.

## Plotly vs Matplotlib vs Seaborn
Matplotlib:
- Static plots
- Highly customizable
- Used for foundational visualization

Seaborn:
- Statistical plots
- Better aesthetics
- EDA focused

Plotly:
- Interactive visualizations
- Modern UI and tooltips
- Best for dashboards and presentations

### Installation and Library Setup 
Before using Plotly, the library must be installed and imported.
Plotly Express is a high-level interface used for quick and simple interactive plots.

In [1]:
# Install plotly library (run only if not installed)

!pip install plotly

Requirement already satisfied: plotly in /home/fm-pc-lt-269/anaconda3/envs/datascience/lib/python3.11/site-packages (6.5.2)
Requirement already satisfied: narwhals>=1.15.1 in /home/fm-pc-lt-269/anaconda3/envs/datascience/lib/python3.11/site-packages (from plotly) (2.17.0)
Requirement already satisfied: packaging in /home/fm-pc-lt-269/anaconda3/envs/datascience/lib/python3.11/site-packages (from plotly) (25.0)

In [2]:
# Import Plotly Express for interactive visualization
import numpy as np 
import pandas as pd
import plotly.express as px
import seaborn as sns 

# Import pandas for dataset handling

# Loading Dataset for Visualization (Reuse Previous Dataset)

To maintain curriculum consistency, we will reuse previously used datasets such as:
- Iris Dataset
- Tips Dataset

This helps students compare static vs interactive visualizations.

In [4]:
# Load a dataset (e.g., iris dataset or tips dataset)
iris = sns.load_dataset("iris")
iris.head()

# Preview the dataset structure

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# Scatter Plot 

A Scatter Plot is used to visualize the relationship between two numerical variables.
With Plotly, the same plot becomes interactive with hover information and zoom functionality.

In [ ]:
# !pip install nbformat

In [6]:
# Create an interactive scatter plot using plotly express
# Select x-axis and y-axis numerical features
# Add color grouping (optional, e.g., species)
# Display the interactive plot

fig = px.scatter(x=[0,1,2,3,4], y = [0,1,4,9,16])
fig.show()

In [9]:
fig = px.scatter(iris, x="sepal_width", y= "sepal_length", color='species', title ="Scatter Plot")
fig.show()

In [11]:
fig = px.scatter(iris, x="sepal_width", y= "sepal_length", color='species', title ="Scatter Plot", size="petal_length")
fig.show()

# Line Plot

A Line Plot is used to observe trends in numerical data.
In Plotly, line plots become interactive, allowing dynamic exploration of trends.

In [13]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
# Create an interactive line plot
# Select feature for x-axis (index or category)
# Select numerical feature for y-axis
# Add title and labels
# Display the interactive visualization

fig = px.line(
    data_frame= iris,
    y="sepal_length",
    title = "Line Plot of Sepal Length"
)
fig.show()

In [18]:
df = px.data.gapminder().query("country == 'Nepal'")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
1068,Nepal,Asia,1952,36.157,9182536,545.865723,NPL,524
1069,Nepal,Asia,1957,37.686,9682338,597.936356,NPL,524
1070,Nepal,Asia,1962,39.393,10332057,652.396859,NPL,524
1071,Nepal,Asia,1967,41.472,11261690,676.442225,NPL,524
1072,Nepal,Asia,1972,43.971,12412593,674.788130,NPL,524
1073,Nepal,Asia,1977,46.748,13933198,694.112440,NPL,524
1074,Nepal,Asia,1982,49.594,15796314,718.373095,NPL,524
1075,Nepal,Asia,1987,52.537,17917180,775.632450,NPL,524
1076,Nepal,Asia,1992,55.727,20326209,897.740360,NPL,524
1077,Nepal,Asia,1997,59.426,23001113,1010.892138,NPL,524
1078,Nepal,Asia,2002,61.340,25873917,1057.206311,NPL,524
1079,Nepal,Asia,2007,63.785,28901790,1091.359778,NPL,524

In [19]:
fig = px.line(
    data_frame=df,
    x="year",
    y="lifeExp",
    title ="Life Expectancy in Nepal"
)
fig.show()

In [22]:
df_continent = px.data.gapminder().query("continent == 'Oceania'")
df_continent

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
60,Australia,Oceania,1952,69.120,8691212,10039.59564,AUS,36
61,Australia,Oceania,1957,70.330,9712569,10949.64959,AUS,36
62,Australia,Oceania,1962,70.930,10794968,12217.22686,AUS,36
63,Australia,Oceania,1967,71.100,11872264,14526.12465,AUS,36
64,Australia,Oceania,1972,71.930,13177000,16788.62948,AUS,36
65,Australia,Oceania,1977,73.490,14074100,18334.19751,AUS,36
66,Australia,Oceania,1982,74.740,15184200,19477.00928,AUS,36
67,Australia,Oceania,1987,76.320,16257249,21888.88903,AUS,36
68,Australia,Oceania,1992,77.560,17481977,23424.76683,AUS,36
69,Australia,Oceania,1997,78.830,18565243,26997.93657,AUS,36
70,Australia,Oceania,2002,80.370,19546792,30687.75473,AUS,36
71,Australia,Oceania,2007,81.235,20434176,34435.36744,AUS,36
1092,New Zealand,Oceania,1952,69.390,1994794,10556.57566,NZL,554
1093,New Zealand,Oceania,1957,70.260,2229407,12247.39532,NZL,554
1094,New Zealand,Oceania,1962,71.240,2488550,13175.67800,NZL,554
1095,New Zealand,Oceania,1967,71.520,2728150,14463.91893,NZL,554
1096,New Zealand,Oceania,1972,71.890,2929100,16046.03728,NZL,554
1097,New Zealand,Oceania,1977,72.220,3164900,16233.71770,NZL,554
1098,New Zealand,Oceania,1982,73.840,3210650,17632.41040,NZL,554
1099,New Zealand,Oceania,1987,74.320,3317166,19007.19129,NZL,554
1100,New Zealand,Oceania,1992,76.330,3437674,18363.32494,NZL,554
1101,New Zealand,Oceania,1997,77.550,3676187,21050.41377,NZL,554
1102,New Zealand,Oceania,2002,79.110,3908037,23189.80135,NZL,554
1103,New Zealand,Oceania,2007,80.204,4115771,25185.00911,NZL,554

In [27]:
fig = px.line(
    data_frame=df_continent,
    x ="year",
    y ="lifeExp",
    color = "country"
)
fig.show()

In [31]:
df = px.data.gapminder().query("country in ['Canada', 'Botswana']")

In [33]:
fig = px.line(
    data_frame= df,
    x ="lifeExp",
    y="gdpPercap",
    color = "country",
    text="year"
)
fig.update_traces(textposition = "bottom right")
fig.show()

#  Bar Plot

Bar plots are used to compare values across different categories.
Plotly bar charts allow hover tooltips showing exact values for better interpretation.

In [34]:
# Create an interactive bar plot
# Select categorical feature for x-axis
# Select numerical feature for y-axis (aggregation concept)
# Add chart title for clarity
# Show the interactive bar chart

fig = px.bar(
    data_frame=iris,
    x ="species",
    y="sepal_length",
    color="species",
    title ="Bar Plot"
)
fig.show()

In [37]:
df_nepal = px.data.gapminder().query("country == 'Nepal'")

In [39]:
fig =px.bar(df_nepal, x ='year', y = "pop")
fig.show()

In [40]:
medal_df = px.data.medals_long()
medal_df

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [41]:
fig = px.bar(medal_df, x ="nation", y="count", color="medal", title="Medal bar graph")
fig.show()

# Histogram (Interactive Distribution Plot)

Histogram shows the distribution of a numerical variable.
In Plotly, histograms allow dynamic bin visualization and hover insights.

In [42]:
# Create an interactive histogram for a numerical feature
# Select dataset and numerical column
# Customize bins (optional)
# Display the histogram

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [47]:
fig = px.histogram(
    iris,
    x="sepal_length",
    title="Histogram ",
    nbins = 20,
    color ="species"
)
fig.show()

## Box Plot in Pyplot

In [48]:
# Create an interactive boxplot
df_tips =px.data.tips()
df_tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [49]:
fig = px.box(
    df_tips,
    y="total_bill",
    title ="BOX Plot of Total Bill"
    
)
fig.show()

In [51]:
fig = px.box(
    df_tips,
    x ="time",
    y="total_bill",
    title ="BOX Plot of Total Bill"
    
)
fig.show()

In [52]:
fig = px.box(
    df_tips,
    x ="time",
    y="total_bill",
    title ="BOX Plot of Total Bill",
    points ='all'
    
)
fig.show()

## Violin Plot in Pyplot

In [53]:
# Create an interactive Violin plot
fig = px.violin(
    df_tips,
    y="total_bill",
    title ="Violin Plot of Total Bill"
)
fig.show()

In [56]:
# Create an interactive Violin plot
fig = px.violin(
    df_tips,
    box = True,
    y="total_bill",
    title ="Violin Plot of Total Bill",
    points = 'all'
)
fig.show()

In [57]:
fig = px.scatter_3d(iris, x='sepal_length', y='sepal_width', z='petal_width',
              color='species')
fig.show()